### ISSUE TITLE
Add support for templates aws_s3_prefix field

### ISSUE THREAD

**Issue by javierquevedo** [aiven/aiven-kafka-connect-s3#1]
Adding support for templates to the  aws_s3_prefix field would be really helpful. For example, it would allow us to store the files in subfolders by date.

Example:
aws_s3_prefix: ` /bucket/folder/${date} `

**Comment by javierquevedo** [comment]
Any plans to address this anytime soon?

**Comment by ivanyu** [comment]
@javierquevedo yep, I will be working on this.

**Comment by ivanyu** [comment]
@javierquevedo is this something you'd like to have: https://github.com/aiven/aiven-kafka-connect-s3/blob/383aa99faa87433548c8caac8b9ee639ce580d65/README.md#aws_s3_prefix ?

**Comment by chasdevs** [comment]
Our company uses a prefix like so: `{source}/{eventName}/{year}/{month}/{day}/{hour}`. Would it be possible to prefix by year/month/day/hour?

**Comment by ivanyu** [comment]
@chasdevs we're re-working the templating approach, it will be more like in the sibling [GCS connector](https://github.com/aiven/aiven-kafka-connect-gcs/#file-name-format). It will give a greater degree of flexibility for configuring file names.

**Comment by ivanyu** [comment]
@joekohlsdorf 2.6.0 should have it
