### ISSUE TITLE
Switch to Java 11

### ISSUE THREAD

**Issue by ivanyu** [aiven/aiven-kafka-connect-s3#16]
https://github.com/aiven/aiven-kafka-connect-s3/blob/master/build.gradle#L45

It should be documented in README, that the connector is targeted at Java 11.

**Comment by a-beloglazov** [comment]
Java version upgraded.

**Comment by ivanyu** [comment]
@a-beloglazov it needs documenting in README (otherwise users spend time on stuff like https://github.com/aiven/aiven-kafka-connect-s3/issues/37)
