### ISSUE TITLE
Refactor configuration definition

### ISSUE THREAD

**Issue by ivanyu** [aiven/aiven-kafka-connect-s3#18]
Connector configuration class `AivenKafkaConnectS3Config` must be brought closer to [`GcsSinkConfig`](https://github.com/aiven/aiven-kafka-connect-gcs/blob/83810ca0d812d0ffca7828ac763e1045d0ac6cd3/src/main/java/io/aiven/kafka/connect/gcs/config/GcsSinkConfig.java#L39) in style. It can be used as the reference.

Some points:
- Rename to `S3SinkConfig`.
- Move constants from `AivenKafkaConnectS3Constants` into the config class.
- Group configurations meaningfully: 
  - use `configDef.define` with `group` parameter;
  - come up with proper groups names;
  - use ordering in groups.
- Add accessor methods like https://github.com/aiven/aiven-kafka-connect-gcs/blob/83810ca0d812d0ffca7828ac763e1045d0ac6cd3/src/main/java/io/aiven/kafka/connect/gcs/config/GcsSinkConfig.java#L379.
- (something else may be missing).

**Comment by a-beloglazov** [comment]
Done
