### ISSUE TITLE
Published artifacts available for download?

### ISSUE THREAD

**Issue by mnaseef-gloo** [aiven/aiven-kafka-connect-s3#59]
Are there artifacts (preferably an uber jar) available somewhere where we can download to install this connector in our self-hosted connect cluster?

**Comment by ivanyu** [comment]
Hi @mnaseef-gloo 
Thank you for the question.
Unfortunately, it's only available on the [releases page](https://github.com/aiven/aiven-kafka-connect-s3/releases).
I've noticed we forgot to attach binary artifacts to the latest release, but I'll fix it in a moment.
In the future, we're going to publish JARs to Maven central or similar repository.

**Comment by mnaseef-gloo** [comment]
Thanks @ivanyu, I don't know if you want to keep this issue open as a reference for publishing JARs, but I'm fine with closing it based on your comment.

**Comment by ivanyu** [comment]
Let's close it them
